### ISSUE TITLE
Intra-sentential models always get learned

### ISSUE THREAD

**Issue by moreymat** [kowey/irit-rst-dt#10]
Intra-sentential models are currently always learned, even if no intra-sentential configuration is enabled:
https://github.com/kowey/irit-rst-dt/blob/scikit/irit_rst_dt/cmd/evaluate.py#L294

**Comment by moreymat** [comment]
This bug is still active, now at
https://github.com/kowey/irit-rst-dt/blob/scikit/irit_rst_dt/cmd/evaluate.py#L284

**Comment by kowey** [comment]
LEARNERS should probably be defined in terms of EVALUATIONS, maybe some
sort of groupby or uniqueness test.

**Comment by moreymat** [comment]
Which means you would do a product of learners and decoders, to later filter the result and retrieve unique learners.

**Comment by kowey** [comment]
Yeah, that's why I didn't do it in the first place.  It's also not related.
But it'd also fix a bug where if you declare perceptrons but don't enable
--post-label, we still generate perceptron models (even if that rules out
the perceptrons)

Anyway, pushing both that and the fix.

**Comment by moreymat** [comment]
Thanks for the fix, works for me.
