### ISSUE TITLE
Non-trivial installation: virtualenv + scipy

### ISSUE THREAD

**Issue by moreymat** [kowey/irit-rst-dt#3]
irit-rst-dt depends on attelo, which in turn depends on scipy.
In a virtualenv, this means scipy has to be built from source using libraries that have to be available system-wide.
If required libraries are not provided, scipy's installation with pip in the virtualenv fails.

I succeeded to install everything by following SciPy's standard instructions for Linux :
> Before building, you will also need to install packages that NumPy and SciPy depend on
> * BLAS and LAPACK libraries (optional but strongly recommended for NumPy, required for SciPy): typically ATLAS + LAPACK, or MKL, or ACML
> * C and Fortran compilers (typically gcc and gfortran).
> * Python header files (typically a package named python-dev or python-devel)
> * Unless you are building from released source packages, the Cython compiler is necessary (typically in a package named cython).

More on http://www.scipy.org/scipylib/building/index.html .

Adding these requirements makes the installation procedure longer and more obscure.
I don't know if there is an easy way around this.

/cc @kowey @phimit

**Comment by kowey** [comment]
Would it help if we promoted Conda instead of Virtualenv? I had no idea it was available outside of the Mac universe, but here you have a guide for [using Conda on Travis](https://gist.github.com/dan-blanchard/7045057)

**Comment by kowey** [comment]
Miniconda seems to work on our Linux cluster, so I declare this fixed by a82abc33
